#Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stemtopoly
email: klai8899@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Fun science activites/experiments that you can do at home!
twitter_username:
github_username:
minimal_mistakes_skin: dark
search: true
search_provider: algolia

google:
    tracking_id:
    anonymize_ip: true

algolia:
    application_id: H3SCC310US
    index_name: test_Kellen
    search_only_api_key: a356b2d993ebc93742017336809da3ba
    powered_by: True

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
# permalink: /:categories/:title/
# paginate: 0 # amount of posts to show
# paginate_path: /page:num/
timezone: Pacific
# logo: "/assets/images/lightbulb.jpg"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
#  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : Stemtopoly
  avatar : "/assets/images/lightbulb.jpg"
  bio    : "Discover science at home"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://example-lai8899.github.io"
    - label: "Villa Park High School"
      icon: "fas fa-fw fa-school"
      url: "https://villaparkhigh.org/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/example-lai8899"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/channel/UCSpuxFtJdmtAVYR-sKrOnDw"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/example-lai8899"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/channel/UCSpuxFtJdmtAVYR-sKrOnDw"
    - label: "Villa Park High School"
      icon: "fas fa-fw fa-school"
      url: "https://villaparkhigh.org/"

defaults:
  # _posts
  #  - scope:
  #      path: ""
  #      type: posts
  #    values:
  #      layout: single
  #      author_profile: true
  #      read_time: false
  #      comments: true
  #     share: true
  #      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

      # category_archive:
      #  type: liquid
      # path: /categories/
      # tag_archive:
      # type: liquid
      # path: /tags/
